server:
  port: 8084

spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/db1?useSSL=false&serverTimezone=UTC
    username: root
    password: 150460
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:

  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.han56.weather.models
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true


#打印sql
logging:
  level:
    com.han56.weather.mapper: debug