server:
  port: 8084

spring:
  profiles:
    active: prod # 本地开发时为dev，预发环境为pre，线上部署时为prod
  config:
    import:
      - classpath:application-${spring.profiles.active}.yml
  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://43.143.225.104:23306/ai_weather_app?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 150460
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties:
        druid:
          stat:
            mergeSql=true;druid:
              stat:
                slowSqlMillis:5000
      use-global-data-source-stat: true

mybatis:

  mapper-locations: classpath:mapper/*.xml

  type-aliases-package: com.han56.weather.models.entity
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#打印sql
logging:
  level:
    com.han56.weather.mapper: debug