server:
  port: 8084

mybatis:
  # ??mapper.xml ???????
  mapper-locations: classpath:mapper/*.xml
  # ??????????
  type-aliases-package: com.han56.weather.models
  # ??????
  configuration:
    map-underscore-to-camel-case: true
#??sql
logging:
  level:
    com.han56.weather.mapper: debug
